# Generated by Django 4.2.5 on 2023-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('beds', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('name_of_hotel', models.CharField(max_length=128)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='rooms_image')),
            ],
        ),
    ]
