# Generated by Django 4.2.5 on 2023-10-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
