# Generated by Django 4.2.5 on 2023-10-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_category_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrooms',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.categories'),
        ),
        migrations.AddField(
            model_name='hotelrooms',
            name='name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
