# Generated by Django 4.2.5 on 2023-10-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_hotelrooms_category_hotelrooms_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hotel', models.CharField(max_length=128)),
                ('prestige', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotelrooms',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotelrooms',
            name='name_of_hotel',
        ),
        migrations.RemoveField(
            model_name='hotelrooms',
            name='prestige',
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
