# Generated by Django 4.2.5 on 2023-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='type',
            new_name='room_class',
        ),
        migrations.AddField(
            model_name='categories',
            name='free_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.IntegerField(choices=[(0, 0), (-1, -1)], default=0),
            preserve_default=False,
        ),
    ]
