# Generated by Django 4.2.5 on 2023-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_type_room_room_class_categories_free_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='free_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
