# Generated by Django 4.2.5 on 2023-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='full_description',
            field=models.TextField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(choices=[('Стандарт', 'Стандарт'), ('Комфорт', 'Комфорт'), ('Семейный', 'Семейный'), ('Престиж', 'Престиж'), ('Бизнес класс', 'Бизнес класс'), ('Люкс', 'Люкс'), ('Люкс VIP', 'Люкс VIP')], max_length=64),
        ),
    ]
