# Generated by Django 4.2.5 on 2023-11-15 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_categories_free_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
