# Generated by Django 4.2.5 on 2023-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_check_in_room_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
